routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Routes - Comfenalco
|--------------------------------------------------------------------------
*/

// Home
Route::get('/', 			'HomeController@index')->name('home');

Auth::routes();

// Panel de Administración Routes...
Route::group(['namespace' => 'Admin', 'prefix' => 'admin','middleware'=>['auth',]], function () {
    // Admin Routes...
    Route::get('/',                         'AdminController@index')->name('admin');
    Route::get('/mi-cuenta/{id}/edit',      'AdminController@edit')->name('usuario.edit');
    Route::put('/mi-cuenta/update/{id}',    'AdminController@update')->name('usuario.update');

    Route::resource('menus',                'MenuController');
    Route::resource('banners',              'BannerController');
    Route::resource('second_banners',       'SecondBannerController');
    Route::get('contenido/listado',         'ContenidoController@listado')->name('contenido.listado');
    Route::resource('contenido',            'ContenidoController');
    Route::resource('tabs',                 'TabsController');
    Route::resource('campanas',             'CampanasController');
    Route::resource('subtabs',              'SubTabController');

    // Proyectos
    Route::resource('proyects',             'ProyectController');
    Route::resource('galleries',            'GalleryController');

    // Eventos
    Route::resource('events',               'EventController');

    // Preguntas frecuentes
    Route::resource('questions',            'FrecuentQuestionController');
    Route::resource('question_categories',  'CategoryQuestionController');

    // Blog
    Route::resource('entries',              'EntryController');
    Route::resource('categories',           'CategoryController');

    // Ordenar category
    Route::get('question_categories/order/category_view', 'CategoryQuestionController@order_edit')->name('question_categories.order.edit');
    Route::post('question_categories/order/category_update', 'CategoryQuestionController@order_update')->name('question_categories.order.update');
    
    // Crear gallery since proyect
    Route::get('galleries/create/proyecto/{proyect_id}', 'GalleryController@create_proyect_gallery')->name('galleries.create.proyect_id');
});

// Menú TOP
Route::get('/organizacion',                 'HomeController@organizacion')->name('organizacion');
Route::get('/afiliado',                     'HomeController@afiliado')->name('afiliado');
Route::get('/servicios-en-linea',           'HomeController@servicios_en_linea')->name('servicios_en_linea');
Route::get('/contactanos',                  'HomeController@contacto')->name('contacto');

// Contacto
Route::post('/contactanos',                 'HomeController@contacto_post')->name('contacto_post');

// Preguntas frecuentes
Route::get('/preguntas-frecuentes',         'HomeController@contacto_preguntas_frecuentes')->name('contacto_preguntas_frecuentes');

// Mapa MyMaps - (templates.páginas)
Route::get('/mapa-comfenalco',              'HomeController@mapa_comfenalco')->name('mapa_comfenalco');

// Blog
Route::get('/informate',                    'Informate\InformateController@informate')->name('informate');
Route::get('/informate/{slug}',             'Informate\InformateController@detalle_de_post')->name('detalle_de_post');
Route::get('/informate/category/{slug}',    'Informate\InformateController@posts_por_categoria')->name('posts_por_categoria');
Route::post('/informate/{slug}',            'Informate\InformateController@post_comment_save')->name('post_comment_save');

// Eventos
Route::get('/eventos',                      'Evento\EventoController@eventos')->name('eventos');
Route::get('/eventos/{slug}',               'Evento\EventoController@detalle_de_evento')->name('detalle_de_evento');

// Página link banner inicio "Empresas"
Route::get('/empresas',                     'HomeController@empresas')->name('empresas');

// Menú principal
Route::get('/afiliaciones',			'Menu\MenuController@afiliaciones')->name('afiliaciones');
Route::get('/educacion',			'Menu\MenuController@educacion')->name('educacion');
Route::get('/vivienda',				'Menu\MenuController@vivienda')->name('vivienda');
Route::get('/recreacion-y-turismo',	'Menu\MenuController@recreacion')->name('recreacion');
Route::get('/proteccion-social',	'Menu\MenuController@proteccion_social')->name('proteccion_social');
Route::get('/deportes',				'Menu\MenuController@deportes')->name('deportes');
Route::get('/cultura',				'Menu\MenuController@cultura')->name('cultura');
Route::get('/agencia-de-empleo',	'Menu\MenuController@agencia_de_empleo')->name('agencia_de_empleo');
Route::get('/credito-social',		'Menu\MenuController@credito_social')->name('credito_social');

// Cargar los proyectos en vivienda
Route::get('/vivienda/proyectos',   'Proyecto\ProyectController@cargar_proyectos')->name('cargar_proyectos');

// Consultar proyectos segun el tipo, la condición y ubicación
Route::post('/vivienda/proyectos',  'Proyecto\ProyectController@busqueda_proyectos')->name('busqueda_proyectos');

// Cargar proyectos por paginación
Route::get('/vivienda/proyectos/page',      'Proyecto\ProyectController@cargar_proyectos_pagination')->name('cargar_proyectos_pagination');

// Cargar información del proyecto
Route::get('/vivienda/proyectos/{slug}',    'Proyecto\ProyectController@cargar_proyecto_slug')->name('cargar_proyecto_slug');

app/Http/Controllers/Proyecto/ProyectController.php
<?php

namespace App\Http\Controllers\Proyecto;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

// Models
use App\Proyect;
use App\Gallery;

class ProyectController extends Controller
{
    public function cargar_proyectos(Request $request){
    	if($request->ajax()) {
            $proyects = Proyect::where('status',1)->paginate(8);
            
            return view('templates.menu-principal.vivienda.proyectos-de-vivienda._cargar-proyectos', compact('proyects'));
        }
        return redirect()->route('vivienda');
    }

    public function cargar_proyecto_slug(Request $request, $slug){
    	if($request->ajax()) {
            $proyect = Proyect::where('slug',$slug)->firstOrFail();
            $galleries = Gallery::where('proyect_id',$proyect->id)->get();
            return view('templates.menu-principal.vivienda.proyectos-de-vivienda._cargar-proyecto-slug', compact('proyect','galleries'));
        }
        return redirect()->route('vivienda');
    }

    public function cargar_proyectos_pagination(Request $request){
        // Paginador
        if($request->ajax()){
            if ($request->session()->has('proyects_store')) {
                $object = $request->session()->get('proyects_store');
                $proyects = Proyect::where('type',$request->session()->get('proyects_store.type'))
                ->where('city','LIKE','%'.$request->session()->get('proyects_store.city').'%')
                ->where('status',1)
                ->OrderBy('created_at','desc')
                ->paginate(8);
                return response()->json(view('templates.menu-principal.vivienda.proyectos-de-vivienda._cargar-proyectos-pagination',compact('proyects'))->render());
            }else{
                $proyects = Proyect::where('status',1)->paginate(8);
                return response()->json(view('templates.menu-principal.vivienda.proyectos-de-vivienda._cargar-proyectos-pagination',compact('proyects'))->render());
            }
        }
        return redirect()->route('vivienda');
    }

    public function busqueda_proyectos(Request $request){
        if($request->ajax()){
            // if ($request->session()->has('proyects_store') && $) {
            //     $object = $request->session()->get('proyects_store');
            //     $proyects = Proyect::where('condition',$request->session()->get('proyects_store.condition'))        
            //     ->where('type',$request->session()->get('proyects_store.type'))
            //     ->where('city','LIKE','%'.$request->session()->get('proyects_store.city').'%')
            //     ->where('status',1)
            //     ->OrderBy('created_at','desc')
            //     ->paginate(8);
            //     return response()->json(view('templates.menu-principal.vivienda.proyectos-de-vivienda._cargar-proyectos-pagination',compact('proyects'))->render());
            // }else{
            //     if($request->session()->has('proyects_store'){

            //     }else{

            //     }
                // obtener datos de consulta
                $type       = $request['type'];
                // $condition  = $request['condition'];
                $city       = $request['city'];

                // busqueda en base de datos según datos obtenidos
                $proyects = Proyect::where('type',$type)
                ->where('city','LIKE','%'.$city.'%')
                ->where('status',1)
                ->OrderBy('created_at','desc')
                ->paginate(8);

                $object = new Proyect();
                $object->type= $type;
                // $object->condition= $condition;
                $object->city= $city;

                $request->session()->put('proyects_store', $object);
                return view('templates.menu-principal.vivienda.proyectos-de-vivienda._cargar-proyectos', compact('proyects'));
            //}
            
        }
        
        return redirect()->route('vivienda');
    }
}

resources/views/templates-admin/proyectos/create.blade.php
@extends('layouts.admin.dashboard')

@section('titulo_dash')
	{{$singular}}
@endsection

@section('styles')
@endsection

@section('titulo_page')
	{{$singular}}
@endsection

@section('content')
	<div class="col-md-12 col-sm-12 col-xs-12">
	    <div class="x_panel">
	      	<div class="x_title">
	        	<h2><i class="fa fa-plus-square"></i> Añadir {{$singular}}</h2>
	        	<div class="clearfix"></div>
	      	</div>
	      	<div class="x_content row">
	      		@if(count($errors)!= 0)
		            <div class="alert alert-warning text-white" role="alert">
						@foreach ($errors->all() as $error)
							<div>{{ $error }}</div>
						@endforeach
		            </div>
		        @endif
		        @include('includes.alert')
		       	<!-- Formulario ADD Proyecto -->
	          	<div class="col-md-10 col-md-offset-1 col-xs-12">
	          		{!! Form::open(['route'=>'proyects.store','method'=> 'POST','files'=>"true", 'enctype'=>"multipart/form-data"]) !!}
		          		{!! csrf_field() !!}
						<div class="form-group">
	                        <label for="title">Nombre</label>
	                        {!! Form::text('title',null,['class'=>'form-control', 'placeholder'=>'']) !!}
	                    </div>
                        <div class="form-group">
                            <label for="thumbnail">Imagen de proyecto (182 x 182 pixeles)</label>
                            {!! Form::file('thumbnail', null, ['class'=>'form-control', 'accept'=>'image/*','required'=>'true']) !!}
                        </div>
                        <div class="form-group">
                           <label>Descripción de imagen / alt</label>
                            {!! Form::text('alt',null,['class'=>'form-control', 'placeholder'=>'opcional']) !!}
                        </div>
                        <div class="form-group table-responsive" id="footer-id">
                            {!! Form::label('description', 'Descripción') !!}
                            <textarea name="description" class="form-control my-editor">{{old('description')}}</textarea>
                        </div>
                        <div class="form-group">
                            <label for="type">Tipo</label>
                            <br>
                            <select class="form-control" name="type" id="type">
                                <option value="">Selecciona un tipo</option>
                                <option value="casa">Casa</option>
                                <option value="apartamento">Apartamento</option>
                            </select>
                        </div> 
                        <div class="form-group">
                            <label for="condition">Condición</label>
                            <br>
                            <select class="form-control" name="condition" id="condition">
								<option value="">Selecciona una condición</option>
                                <option value="venta">Venta</option>
                            </select>
                        </div> 
                        <div class="form-group">
	                        <label for="city">Ciudad</label>
	                        {!! Form::text('city',null,['class'=>'form-control', 'placeholder'=>'Digita una Ciudad']) !!}
	                    </div>
	                    <div class="form-group">
	                        <label for="neighborhood">Barrio</label>
	                        {!! Form::text('neighborhood',null,['class'=>'form-control', 'placeholder'=>'Digita un Barrio']) !!}
	                    </div>
                        {{-- <div class="form-group">
                            <label for="destacado">Nivel de importancia de un proyecto (1 a 5)</label>
                            <br>
                            <select class="form-control" name="destacado" id="destacado_input">
                                <option value="1">1 (Menos importante)</option>
                                <option value="2">2</option>
                                <option value="3" selected>3</option>
                                <option value="4">4</option>
                                <option value="5">5 (Más importante)</option>
                            </select>
                        </div> --}}
                        <div class="form-group">
                            <label for="status">Estado</label>
                            <select class="form-control" name="status" id="estado">
                                <option value="1" selected>Publicado</option>
                                <option value="0">No publicado</option>
                            </select>
                        </div>
                    {!! Form::submit('Guardar Proyecto',['class'=>'center-block btn btn-success']) !!}
		          	{!! Form::close() !!}
	          	</div>
	      	</div>
		</div>
	</div>
@endsection

@section('scripts')
	@include('includes.tinymce')
@endsection

resources/views/templates-admin/proyectos/edit.blade.php
@extends('layouts.admin.dashboard')

@section('titulo_dash')
    {{$singular}}
@endsection

@section('styles')
@endsection

@section('titulo_page')
    {{$singular}}
@endsection

@section('content')
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2><i class="fa fa-plus-square"></i> Modificar {{$singular}}</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content row">
                @if ($errors->any())
                <div class="alert alert-danger text-white" role="alert">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
                @include('includes.alert')
                <div class="col-md-10 col-md-offset-1 col-xs-12">
                    {!! Form::model($object, ['route'=>['proyects.update', $object->id],'method'=>'PUT','class'=>'form-horizontal', 'files'=>"true", 'enctype'=>"multipart/form-data"]) !!}
                        {!! csrf_field() !!}
                        <div class="form-group">
                            <label for="title">Título *</label>
                            {!! Form::text('title',null,['class'=>'form-control', 'placeholder'=>'', 'required'=>'true']) !!}
                        </div>
                        <div class="form-group">
                            <label for="slug">Slug (<em>Opcional</em>)</label>
                            {!! Form::text('slug',null,['class'=>'form-control', 'placeholder'=>'Título para URL donde se elimnan los espacios vacios', 'required'=>'true']) !!}
                        </div>
                        <div class="form-group">
                            <label for="thumbnail">Cambiar imagen</label>
                            {!! Form::file('thumbnail',['class'=>'form-control', 'id'=>'file-upload','accept'=>'image/*']) !!}
                        </div>
                        <div class="form-group">
                            {!! Form::label('Previsualizar') !!}
                            <br>
                            <div id="file-preview-zonsse">
                                <img src="{{asset('proyect_images/'.$object->thumbnail)}}" alt="" id="file-preview" style="width: 200px;height: 100px;">
                            </div>
                        </div>
                        <div class="form-group">
                           <label for="alt">Descripción de imagen / alt</label>
                            {!! Form::text('alt',null,['class'=>'form-control', 'placeholder'=>'Campo opcional']) !!}
                        </div>
                        <div class="form-group table-responsive" id="footer-id">
                            {!! Form::label('description', 'Descripción') !!}
                            {!! Form::textarea('description',old('description'),['class'=>'form-control my-editor','placeholder'=>'']) !!}
                        </div>
                        <div class="form-group">
                            <label for="type">Tipo</label>
                            <br>
                            <select class="form-control" name="type" id="type">
                                <option value="casa" @if($object->type=='casa') selected @endif>Casa</option>
                                <option value="apartamento" @if($object->type=='apartamento') selected @endif>Apartamento</option>
                            </select>
                        </div> 
                        <div class="form-group">
                            <label for="condition">Condición</label>
                            <br>
                            <select class="form-control" name="condition" id="condition">
                                <option value="venta" @if($object->condition=='venta') selected @endif>Venta</option>
                            </select>
                        </div> 
                        <div class="form-group">
                            <label for="city">Ciudad</label>
                            {!! Form::text('city',null,['class'=>'form-control', 'placeholder'=>'Digita una Ciudad']) !!}
                        </div>
                        <div class="form-group">
                            <label for="neighborhood">Barrio</label>
                            {!! Form::text('neighborhood',null,['class'=>'form-control', 'placeholder'=>'Digita un Barrio']) !!}
                        </div>
                        <div class="form-group">
                            <label for="status">Estado</label>
                            <select class="form-control" name="status" id="estado">
                                <option value="1" @if($object->status==1) selected @endif>Publicado</option>
                                <option value="0" @if($object->status==0) selected @endif>No publicado</option>
                            </select>
                        </div>
                    {!! Form::submit('Actualizar '.$singular,['class'=>'center-block btn btn-success']) !!}
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script type="text/javascript">  
        function readFile(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    var filePreview = document.getElementById('file-preview');
                    filePreview.src = e.target.result;
                };

                reader.readAsDataURL(input.files[0]);
            }
        }

        var fileUpload = document.getElementById('file-upload');
        fileUpload.onchange = function (e) {
            readFile(e.srcElement);
        }
    </script> 
    @include('includes.tinymce')
    <script>
        $('#boo-resumen').click(function(){
            $('#form-oculto').slideToggle();
        });
    </script>
@endsection

resources/views/templates-admin/proyectos/index.blade.php
@extends('layouts.admin.dashboard')

@section('titulo_dash')
	{{$plural}}
@endsection

@section('style')
@endsection

@section('titulo_page')
	{{$plural}}
@endsection

@section('content')
	<div class="col-md-12 col-sm-12 col-xs-12">
	    <div class="x_panel">
	      	<div class="x_title">
	        	<h2><i class="fa fa-list"></i> Listar {{$plural}}</h2>
	        	<div class="clearfix"></div>
	      	</div>
	      	<div class="x_content row">
	      		@include('includes.alert')
	          	<div class="col-xs-12">
					<div class="table-responsive">
					    <table id="example" class="table table-striped table-bordered dataTable" cellspacing="0" width="100%">
					        <thead>
						        <tr>
						        	<th>#</th>
						        	<th>Título</th>
						            <th>Imagen</th>
						            <th>Tipo</th>
									<th>Condición</th>
									<th>Ubicación</th>
									<th>Estado</th>
									<th>Gallería</th>
						            <th>Acción</th>
						        </tr>
					        </thead>
					        <tbody>
					        @forelse($objects as $object)
					            <tr>
					            	<td>{{$loop->iteration}}</td>
					            	<td>{{$object->title}}</td>
									<td><img width="100" height="100" src="{{ asset('proyect_images/'.$object->thumbnail)}}" alt="">{{$object->alt}}</td>
									<td>{{$object->type}}</td>
									<td>{{$object->condition}}</td>
									<td>{{$object->city."/".$object->neighborhood}}</td>
									<td>
										@if($object->status == 0)
											No publicado
										@else 
											Publicado
										@endif
									</td>
									<td><a href="{{ route('galleries.show',$object->id) }}" class="btn btn-success">Ver gallería</a> ({{count($object->galleries)}})</td>
									<td style="width:10%">
										<ul style="list-style: none;padding-left: 0;">
											<li style="display:inline-block;vertical-align: top">
												{!! Form::open(['route'=>['proyects.destroy',$object->id],'method'=>'DELETE'])!!}
												{{ csrf_field() }}
								               		<button onclick="return confirm('¿Está seguro de eliminar permanentemente el proyecto {{$object->title}}?');" class="btn btn-danger btn-block text-left" type="submit"><i class="fa fa-remove" aria-hidden="true"></i></button>
								                {!! Form::close() !!}
						            		</li>
											<li style="display:inline-block">
												<a href="{{URL::route('proyects.edit',$object->id)}}" class="btn btn-primary btn-block text-left"><i class="fa fa-pencil"></i></a>
											</li>
										</ul>
									</td>
					            </tr>
					        @empty
					            <div class="alert alert-dismissable alert-warning text-white">
					                <button type="button" class="close" data-dismiss="alert">×</button>
					                <h4>Mensaje del sistema!</h4>
					                <p>Ups!, no se encontraron {{$plural}}.</p>
					            </div>
					            <td colspan="9">No hay {{$plural}} para mostrar</td>
					        @endforelse
					        </tbody>
					    </table>
					</div>		      		    			
	          	</div>
	      	</div>
		</div>
	</div>
@endsection

@section('script')
@endsection