routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Routes - Comfenalco
|--------------------------------------------------------------------------
*/

// Home
Route::get('/', 			'HomeController@index')->name('home');

Auth::routes();

// Panel de Administración Routes...
Route::group(['namespace' => 'Admin', 'prefix' => 'admin','middleware'=>['auth',]], function () {
    // Admin Routes...
    Route::get('/',                         'AdminController@index')->name('admin');
    Route::get('/mi-cuenta/{id}/edit',      'AdminController@edit')->name('usuario.edit');
    Route::put('/mi-cuenta/update/{id}',    'AdminController@update')->name('usuario.update');

    Route::resource('menus',                'MenuController');
    Route::resource('banners',              'BannerController');
    Route::resource('second_banners',       'SecondBannerController');
    Route::get('contenido/listado',         'ContenidoController@listado')->name('contenido.listado');
    Route::resource('contenido',            'ContenidoController');
    Route::resource('tabs',                 'TabsController');
    Route::resource('campanas',             'CampanasController');
    Route::resource('subtabs',              'SubTabController');

    // Proyectos
    Route::resource('proyects',             'ProyectController');
    Route::resource('galleries',            'GalleryController');

    // Eventos
    Route::resource('events',               'EventController');

    // Preguntas frecuentes
    Route::resource('questions',            'FrecuentQuestionController');
    Route::resource('question_categories',  'CategoryQuestionController');

    // Blog
    Route::resource('entries',              'EntryController');
    Route::resource('categories',           'CategoryController');

    // Ordenar category
    Route::get('question_categories/order/category_view', 'CategoryQuestionController@order_edit')->name('question_categories.order.edit');
    Route::post('question_categories/order/category_update', 'CategoryQuestionController@order_update')->name('question_categories.order.update');
    
    // Crear gallery since proyect
    Route::get('galleries/create/proyecto/{proyect_id}', 'GalleryController@create_proyect_gallery')->name('galleries.create.proyect_id');
});

// Menú TOP
Route::get('/organizacion',                 'HomeController@organizacion')->name('organizacion');
Route::get('/afiliado',                     'HomeController@afiliado')->name('afiliado');
Route::get('/servicios-en-linea',           'HomeController@servicios_en_linea')->name('servicios_en_linea');
Route::get('/contactanos',                  'HomeController@contacto')->name('contacto');

// Contacto
Route::post('/contactanos',                 'HomeController@contacto_post')->name('contacto_post');

// Preguntas frecuentes
Route::get('/preguntas-frecuentes',         'HomeController@contacto_preguntas_frecuentes')->name('contacto_preguntas_frecuentes');

// Mapa MyMaps - (templates.páginas)
Route::get('/mapa-comfenalco',              'HomeController@mapa_comfenalco')->name('mapa_comfenalco');

// Blog
Route::get('/informate',                    'Informate\InformateController@informate')->name('informate');
Route::get('/informate/{slug}',             'Informate\InformateController@detalle_de_post')->name('detalle_de_post');
Route::get('/informate/category/{slug}',    'Informate\InformateController@posts_por_categoria')->name('posts_por_categoria');
Route::post('/informate/{slug}',            'Informate\InformateController@post_comment_save')->name('post_comment_save');

// Eventos
Route::get('/eventos',                      'Evento\EventoController@eventos')->name('eventos');
Route::get('/eventos/{slug}',               'Evento\EventoController@detalle_de_evento')->name('detalle_de_evento');

// Página link banner inicio "Empresas"
Route::get('/empresas',                     'HomeController@empresas')->name('empresas');

// Menú principal
Route::get('/afiliaciones',			'Menu\MenuController@afiliaciones')->name('afiliaciones');
Route::get('/educacion',			'Menu\MenuController@educacion')->name('educacion');
Route::get('/vivienda',				'Menu\MenuController@vivienda')->name('vivienda');
Route::get('/recreacion-y-turismo',	'Menu\MenuController@recreacion')->name('recreacion');
Route::get('/proteccion-social',	'Menu\MenuController@proteccion_social')->name('proteccion_social');
Route::get('/deportes',				'Menu\MenuController@deportes')->name('deportes');
Route::get('/cultura',				'Menu\MenuController@cultura')->name('cultura');
Route::get('/agencia-de-empleo',	'Menu\MenuController@agencia_de_empleo')->name('agencia_de_empleo');
Route::get('/credito-social',		'Menu\MenuController@credito_social')->name('credito_social');

// Cargar los proyectos en vivienda
Route::get('/vivienda/proyectos',   'Proyecto\ProyectController@cargar_proyectos')->name('cargar_proyectos');

// Consultar proyectos segun el tipo, la condición y ubicación
Route::post('/vivienda/proyectos',  'Proyecto\ProyectController@busqueda_proyectos')->name('busqueda_proyectos');

// Cargar proyectos por paginación
Route::get('/vivienda/proyectos/page',      'Proyecto\ProyectController@cargar_proyectos_pagination')->name('cargar_proyectos_pagination');

// Cargar información del proyecto
Route::get('/vivienda/proyectos/{slug}',    'Proyecto\ProyectController@cargar_proyecto_slug')->name('cargar_proyecto_slug');

app/Tab.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tab extends Model
{
    public function sub_tabs(){
    	return $this->hasMany('App\SubTab', 'tabs_id');
    }
    public function second_banners(){
    	return $this->hasMany('App\SecondBanner', 'tabs_id');
    }
}

app/Http/Controllers/Admin/TabsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Tab as Tab;
use App\Menu as Menu;

class TabsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tabs = Tab::all();
        $menu = Menu::all();
        return view('templates-admin.tabs.principal.index', compact('menu', 'tabs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $menus = Menu::all();
        return view('templates-admin.tabs.principal.create', compact('menus'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $store = new Tab;
        $store->title = $request->input('title');
        $store->slug = str_slug($request->input('title'));
        $store->description = $request->input('description');
        $store->menus_id = $request->input('menus_id');
        if ($request->hasFile('thumbnail')) {
           $fileas = $request->file('thumbnail');
           $destinationPathas = 'img/img-tabs/';
           $fileas->move($destinationPathas,$fileas->getClientOriginalName());
           $store->image = $destinationPathas.''.$fileas->getClientOriginalName();
        }else{
           $store->image = 'img/img-tabs/logo.png';
        }
        $store->save();
        return back()->with('success','Se guardó su item correctamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $tabs = Tab::find($id);
        return view('templates-admin.tabs.principal.show', compact('tabs'));
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tabs = Tab::find($id);
        $menu = Menu::all();
        return view('templates-admin.tabs.principal.edit', compact('menu', 'tabs'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $store = Tab::find($id);
        $store->title = $request->input('title');
        $store->slug = str_slug($request->input('title'));
        $store->description = $request->input('description');
        if ($request->hasFile('thumbnail')) {
           $fileas = $request->file('thumbnail');
           $destinationPathas = 'img/img-tabs/';
           $fileas->move($destinationPathas,$fileas->getClientOriginalName());
           $store->image = $destinationPathas.''.$fileas->getClientOriginalName();
        }
        $store->update();
        return back()->with('success','Se actualizó su item correctamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $store = Tab::find($id);
        $store->delete();
        return back()->with('success','Se eliminó su item correctamente');
    }
}

resources/views/templates-admin/tabs/principal/create.blade.php
@extends('layouts.admin.dashboard')

@section('titulo_dash')
@endsection

@section('styles')
@endsection

@section('titulo_page')
    Tabs principales
@endsection

@section('content')
	<div class="col-md-12 col-sm-12 col-xs-12">
	    <div class="x_panel">
	      	<div class="x_title">
	        	<h2><i class="fa fa-plus-square"></i> Añadir </h2>
	        	<div class="clearfix"></div>
	      	</div>
	      	<div class="x_content row">
	      		@if(count($errors)!= 0)
		            <div class="alert alert-warning text-white" role="alert">
						@foreach ($errors->all() as $error)
							<div>{{ $error }}</div>
						@endforeach
		            </div>
		        @endif
		        @include('includes.alert')
		       	<!-- Formulario ADD Proyecto -->
	          	<div class="col-md-10 col-md-offset-1 col-xs-12">
	          		{!! Form::open(['route'=>'tabs.store','method'=> 'POST','files'=>"true", 'enctype'=>"multipart/form-data"]) !!}
		          		{!! csrf_field() !!}
						<div class="form-group">
	                        <label for="title">Titulo del tab</label>
	                        {!! Form::text('title',null,['class'=>'form-control', 'placeholder'=>'']) !!}
	                    </div>
                        {{-- <div class="form-group">
                            <label for="thumbnail">Imagen de tab (182 x 182 pixeles)</label>
                            {!! Form::file('thumbnail', null, ['class'=>'form-control', 'accept'=>'image/*','required'=>'true']) !!}
                        </div> --}}
                        {{-- <div class="form-group">
                           <label>Slug menu</label>
                            {!! Form::text('slug',null,['class'=>'form-control', 'placeholder'=>'opcional']) !!}
                        </div> --}}
                        <div class="form-group table-responsive" id="footer-id">
                            {!! Form::label('description', 'Descripción') !!}
                            <textarea name="description" class="form-control my-editor">{{old('description')}}</textarea>
                        </div>
                        <div class="form-group">
                            <label for="type">Sección de tabs</label>
                            <br>
                            <select class="form-control" name="menus_id" id="type">
                                <option value="">Selecciona un tipo</option>
                                @if(isset($menus))
                                    @foreach($menus as $menu)
                                        <option value="{{ $menu['id'] }}">{{ $menu['title'] }}</option>
                                    @endforeach
                                @endif
                            </select>
                        </div> 
                        {{-- <div class="form-group">
                            <label for="condition">Condición</label>
                            <br>
                            <select class="form-control" name="condition" id="condition">
								<option value="">Selecciona una condición</option>
                                <option value="venta">Venta</option>
                                <option value="arriendo">Arriendo</option>
                            </select>
                        </div> 
                        <div class="form-group">
	                        <label for="city">Ciudad</label>
	                        {!! Form::text('city',null,['class'=>'form-control', 'placeholder'=>'Digita una Ciudad']) !!}
	                    </div>
	                    <div class="form-group">
	                        <label for="neighborhood">Barrio</label>
	                        {!! Form::text('neighborhood',null,['class'=>'form-control', 'placeholder'=>'Digita un Barrio']) !!}
	                    </div> --}}
                        {{-- <div class="form-group">
                            <label for="destacado">Nivel de importancia de un proyecto (1 a 5)</label>
                            <br>
                            <select class="form-control" name="destacado" id="destacado_input">
                                <option value="1">1 (Menos importante)</option>
                                <option value="2">2</option>
                                <option value="3" selected>3</option>
                                <option value="4">4</option>
                                <option value="5">5 (Más importante)</option>
                            </select>
                        </div> --}}
                        <div class="form-group">
                            <label for="status">Estado</label>
                            <select class="form-control" name="status" id="estado">
                                <option value="1" selected>Publicado</option>
                                <option value="0">No publicado</option>
                            </select>
                        </div>
                    {!! Form::submit('Guardar tab',['class'=>'center-block btn btn-success']) !!}
		          	{!! Form::close() !!}
	          	</div>
	      	</div>
		</div>
	</div>
@endsection

@section('scripts')
	@include('includes.tinymce')
@endsection

resources/views/templates-admin/tabs/principal/edit.blade.php
@extends('layouts.admin.dashboard')

@section('titulo_dash')
@endsection

@section('styles')
@endsection

@section('titulo_page')
@endsection

@section('content')
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2><i class="fa fa-plus-square"></i> Modificar {{ $tabs['title']}}</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content row">
                @if ($errors->any())
                <div class="alert alert-danger text-white" role="alert">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
                @include('includes.alert')
                <div class="col-md-10 col-md-offset-1 col-xs-12">
                    {!! Form::model($tabs, ['route'=>['tabs.update', $tabs->id],'method'=>'PUT','class'=>'form-horizontal', 'files'=>"true", 'enctype'=>"multipart/form-data"]) !!}
                        {!! csrf_field() !!}
                        <div class="form-group">
                            <label for="title">Título *</label>
                            {!! Form::text('title',null,['class'=>'form-control', 'placeholder'=>'', 'required'=>'true']) !!}
                        </div>
                        <div class="form-group">
                            <label for="slug">Slug (<em>Opcional</em>)</label>
                            {!! Form::text('slug',null,['class'=>'form-control', 'placeholder'=>'Título para URL donde se elimnan los espacios vacios', 'required'=>'true']) !!}
                        </div>
                        <div class="form-group table-responsive" id="footer-id">
                            {!! Form::label('description', 'Descripción') !!}
                            {!! Form::textarea('description',old('description'),['class'=>'form-control my-editor','placeholder'=>'']) !!}
                        </div>
                        <div class="form-group">
                            <label for="type">Tipo de contacto</label>
                            <br>
                            <select class="form-control" name="type" id="type">
                                <option value="0" @if($tabs->type_contact == 0) selected @endif>Tipo 1</option>
                                <option value="1" @if($tabs->type_contact == 1) selected @endif>Tipo 2</option>
                            </select>
                        </div> 
                        <div class="form-group">
                            <label for="status">Estado</label>
                            <select class="form-control" name="status" id="estado">
                                <option value="1" @if($tabs->status==1) selected @endif>Publicado</option>
                                <option value="0" @if($tabs->status==0) selected @endif>No publicado</option>
                            </select>
                        </div>
                    {!! Form::submit('Actualizar '.$tabs['title'],['class'=>'center-block btn btn-success']) !!}
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts') 
    @include('includes.tinymce')
    <script>
        $('#boo-resumen').click(function(){
            $('#form-oculto').slideToggle();
        });
    </script>
@endsection

resources/views/templates-admin/tabs/principal/index.blade.php
@extends('layouts.admin.dashboard')

@section('titulo_dash')
@endsection

@section('style')
@endsection

@section('titulo_page')
@endsection

@section('content')
	<div class="col-md-12 col-sm-12 col-xs-12">
	    <div class="x_panel">
	      	<div class="x_title">
	        	<h2><i class="fa fa-list"></i> Listar </h2>
	        	<div class="clearfix"></div>
	      	</div>
	      	<div class="x_content row">
	      		@include('includes.alert')
	          	<div class="col-xs-12">
					<div class="table-responsive">
					    <table id="example" class="table table-striped table-bordered dataTable" cellspacing="0" width="100%">
					        <thead>
						        <tr>
						        	<th>#</th>
						            <th>Titulo</th>
						            <th>Slug</th>
									<th>Descripcion</th>
						            <th>Tipo_contacto</th>
						            <th>Sub tabs</th>
						            <th>Acción</th>
						        </tr>
					        </thead>
					        <tbody>
					        @forelse($tabs as $object)
					            <tr>
					            	<td>{{$loop->iteration}}</td>
									<td>{{$object->title}} 
										{{-- @foreach($object->sub_tabs as $o)
											<br>{{ $o['title'] }} <br>
										@endforeach --}}
									</td>
									<td>{{$object->slug}}</td>
									<td>{!! \Illuminate\Support\Str::words(strip_tags($object->description),80) !!}</td>
									<td>{{$object->type_contact}}</td>
									<td><a href="{{ route('tabs.show',$object->id) }}" class="btn btn-success">Ver sub tabs</a> ({{count($object->sub_tabs)}})</td>
									<td style="width:10%">
										<ul style="list-style: none;padding-left: 0;">
											<li style="display:inline-block;vertical-align: top">
												{!! Form::open(['route'=>['tabs.destroy',$object->id],'method'=>'DELETE'])!!}
								               		<button onclick="return confirm('¿Está seguro de eliminar permanentemente el item?');" class="btn btn-danger btn-block text-left" type="submit"><i class="fa fa-remove" aria-hidden="true"></i></button>
								                {!! Form::close() !!}
						            		</li>
						            		<li style="display:inline-block">
												<a href="{{URL::route('tabs.edit',$object->id)}}" class="btn btn-primary btn-block text-left"><i class="fa fa-pencil"></i></a>
											</li>
										</ul>
									</td>
					            </tr>
					        @empty
					            <div class="alert alert-dismissable alert-warning text-white">
					                <button type="button" class="close" data-dismiss="alert">×</button>
					                <h4>Mensaje del sistema!</h4>
					                <p>Ups!, no se encontraron tabs.</p>
					            </div>
					            <td colspan="9">No hay tabs para mostrar</td>
					        @endforelse
					        </tbody>
					    </table>
					</div>		      		    			
	          	</div>
	      	</div>
		</div>
	</div>
@endsection

@section('script')
@endsection

resources/views/templates-admin/tabs/principal/show.blade.php
@extends('layouts.admin.dashboard')

@section('titulo_dash')
@endsection

@section('style')
@endsection

@section('titulo_page')
	Sub Tabs
@endsection

@section('content')
	<div class="col-md-12 col-sm-12 col-xs-12">
	    <div class="x_panel">
	      	<div class="x_title">
	        	<h2><i class="fa fa-list"></i> Listar Sub tabs / <a style="text-decoration: underline;" href="{{ route('tabs.index') }}">{{$tabs->title}}</a></h2>
	        	<div class="clearfix"></div>
	      	</div>
	      	<div class="x_content row">
	      		@include('includes.alert')
	      		<div class="row">
		      		<div class="col-xs-12">
		      			<a class="btn btn-success pull-right" href="{{ route('subtabs.create') }}?tab={{ $tabs->id }}"><i class="fa fa-plus"></i> Agregar Sub tabs</a>
		      		</div>
	      		</div>
	          	<div class="col-xs-12">
					<div class="table-responsive">
					    <table id="example" class="table table-striped table-bordered dataTable" cellspacing="0" width="100%">
					        <thead>
						        <tr>
						        	<th>#</th>
						            <th>Titulo</th>
						            <th>Descripción</th>
						            <th>Slug</th>
						            <th>Acción</th>
						        </tr>
					        </thead>
					        <tbody>
					        @forelse($tabs->sub_tabs as $object)
					            <tr>
					            	<td>{{$loop->iteration}}</td>
									<td>{{$object->title}}</td>
									<td>@if($object->alt) {{$object->alt}} @else No tiene descripción @endif</td>
									<td>{{$object->slug}}</td>
									{{-- <td>
										@if($object->status == 0)
											No publicado
										@else 
											Publicado
										@endif
									</td> --}}
									<td style="width:10%">
										<ul style="list-style: none;padding-left: 0;">
											<li style="display:inline-block;vertical-align: top">
												{!! Form::open(['route'=>['subtabs.destroy',$object->id],'method'=>'DELETE'])!!}
								               		<button onclick="return confirm('¿Está seguro/a de eliminar permanentemente este item {{$object->alt}}?');" class="btn btn-danger btn-block text-left" type="submit"><i class="fa fa-remove" aria-hidden="true"></i></button>
								                {!! Form::close() !!}
						            		</li>
						            		<li style="display:inline-block">
												<a href="{{URL::route('subtabs.edit',$object->id)}}" class="btn btn-primary btn-block text-left"><i class="fa fa-pencil"></i></a>
											</li>
										</ul>
									</td>
					            </tr>
					        @empty
					            <div class="alert alert-dismissable alert-warning text-white">
					                <button type="button" class="close" data-dismiss="alert">×</button>
					                <h4>Mensaje del sistema!</h4>
					                <p>Ups!, no se encontraron Sub tabs.</p>
					            </div>
					            <td colspan="4">No hay Sub tabs para mostrar</td>
					        @endforelse
					        </tbody>
					    </table>
					</div>		      		    			
	          	</div>
	      	</div>
		</div>
	</div>
@endsection

@section('script')
@endsection