routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Routes - Comfenalco
|--------------------------------------------------------------------------
*/

// Home
Route::get('/', 			'HomeController@index')->name('home');

Auth::routes();

// Panel de Administración Routes...
Route::group(['namespace' => 'Admin', 'prefix' => 'admin','middleware'=>['auth',]], function () {
    // Admin Routes...
    Route::get('/',                         'AdminController@index')->name('admin');
    Route::get('/mi-cuenta/{id}/edit',      'AdminController@edit')->name('usuario.edit');
    Route::put('/mi-cuenta/update/{id}',    'AdminController@update')->name('usuario.update');

    Route::resource('menus',                'MenuController');
    Route::resource('banners',              'BannerController');
    Route::resource('second_banners',       'SecondBannerController');
    Route::get('contenido/listado',         'ContenidoController@listado')->name('contenido.listado');
    Route::resource('contenido',            'ContenidoController');
    Route::resource('tabs',                 'TabsController');
    Route::resource('campanas',             'CampanasController');
    Route::resource('subtabs',              'SubTabController');

    // Proyectos
    Route::resource('proyects',             'ProyectController');
    Route::resource('galleries',            'GalleryController');

    // Eventos
    Route::resource('events',               'EventController');

    // Preguntas frecuentes
    Route::resource('questions',            'FrecuentQuestionController');
    Route::resource('question_categories',  'CategoryQuestionController');

    // Blog
    Route::resource('entries',              'EntryController');
    Route::resource('categories',           'CategoryController');

    // Ordenar category
    Route::get('question_categories/order/category_view', 'CategoryQuestionController@order_edit')->name('question_categories.order.edit');
    Route::post('question_categories/order/category_update', 'CategoryQuestionController@order_update')->name('question_categories.order.update');
    
    // Crear gallery since proyect
    Route::get('galleries/create/proyecto/{proyect_id}', 'GalleryController@create_proyect_gallery')->name('galleries.create.proyect_id');
});

// Menú TOP
Route::get('/organizacion',                 'HomeController@organizacion')->name('organizacion');
Route::get('/afiliado',                     'HomeController@afiliado')->name('afiliado');
Route::get('/servicios-en-linea',           'HomeController@servicios_en_linea')->name('servicios_en_linea');
Route::get('/contactanos',                  'HomeController@contacto')->name('contacto');

// Contacto
Route::post('/contactanos',                 'HomeController@contacto_post')->name('contacto_post');

// Preguntas frecuentes
Route::get('/preguntas-frecuentes',         'HomeController@contacto_preguntas_frecuentes')->name('contacto_preguntas_frecuentes');

// Mapa MyMaps - (templates.páginas)
Route::get('/mapa-comfenalco',              'HomeController@mapa_comfenalco')->name('mapa_comfenalco');

// Blog
Route::get('/informate',                    'Informate\InformateController@informate')->name('informate');
Route::get('/informate/{slug}',             'Informate\InformateController@detalle_de_post')->name('detalle_de_post');
Route::get('/informate/category/{slug}',    'Informate\InformateController@posts_por_categoria')->name('posts_por_categoria');
Route::post('/informate/{slug}',            'Informate\InformateController@post_comment_save')->name('post_comment_save');

// Eventos
Route::get('/eventos',                      'Evento\EventoController@eventos')->name('eventos');
Route::get('/eventos/{slug}',               'Evento\EventoController@detalle_de_evento')->name('detalle_de_evento');

// Página link banner inicio "Empresas"
Route::get('/empresas',                     'HomeController@empresas')->name('empresas');

// Menú principal
Route::get('/afiliaciones',			'Menu\MenuController@afiliaciones')->name('afiliaciones');
Route::get('/educacion',			'Menu\MenuController@educacion')->name('educacion');
Route::get('/vivienda',				'Menu\MenuController@vivienda')->name('vivienda');
Route::get('/recreacion-y-turismo',	'Menu\MenuController@recreacion')->name('recreacion');
Route::get('/proteccion-social',	'Menu\MenuController@proteccion_social')->name('proteccion_social');
Route::get('/deportes',				'Menu\MenuController@deportes')->name('deportes');
Route::get('/cultura',				'Menu\MenuController@cultura')->name('cultura');
Route::get('/agencia-de-empleo',	'Menu\MenuController@agencia_de_empleo')->name('agencia_de_empleo');
Route::get('/credito-social',		'Menu\MenuController@credito_social')->name('credito_social');

// Cargar los proyectos en vivienda
Route::get('/vivienda/proyectos',   'Proyecto\ProyectController@cargar_proyectos')->name('cargar_proyectos');

// Consultar proyectos segun el tipo, la condición y ubicación
Route::post('/vivienda/proyectos',  'Proyecto\ProyectController@busqueda_proyectos')->name('busqueda_proyectos');

// Cargar proyectos por paginación
Route::get('/vivienda/proyectos/page',      'Proyecto\ProyectController@cargar_proyectos_pagination')->name('cargar_proyectos_pagination');

// Cargar información del proyecto
Route::get('/vivienda/proyectos/{slug}',    'Proyecto\ProyectController@cargar_proyecto_slug')->name('cargar_proyecto_slug');

resources/views/templates-admin/entradas/categorias/create.blade.php
@extends('layouts.admin.dashboard')

@section('titulo_dash')
	Categorías
@endsection

@section('styles')
@endsection

@section('titulo_page')
	Categorías
@endsection

@section('content')
	<div class="col-md-12 col-sm-12 col-xs-12">
	    <div class="x_panel">
	      	<div class="x_title">
	        	<h2><i class="fa fa-plus-square"></i> Añadir Categoría</h2>
	        	<div class="clearfix"></div>
	      	</div>
	      	<div class="x_content row">
	      		@if(count($errors)!= 0)
		            <div class="alert alert-warning text-white" role="alert">
						@foreach ($errors->all() as $error)
							<div>{{ $error }}</div>
						@endforeach
		            </div>
		        @endif
		        @include('includes.alert')
	          	<!-- Formulario ADD CATEGORY -->
	          	<div class="col-md-10 col-md-offset-1 col-xs-12">
	          		{!! Form::open(['route'=>'categories.store','method'=> 'POST']) !!}
		          		{!! csrf_field() !!}
		          		<div class="form-group">
	                        <label for="name">Nombre *</label>
	                        {!! Form::text('name',null,['class'=>'form-control', 'placeholder'=>'', 'required'=>'true']) !!}
	                    </div>
                    {!! Form::submit('Guardar Categoría',['class'=>'center-block btn btn-success']) !!}
		          	{!! Form::close() !!}
	          	</div>
	      	</div>
		</div>
	</div>
@endsection

@section('scripts')
@endsection

resources/views/templates-admin/entradas/categorias/edit.blade.php
@extends('layouts.admin.dashboard')

@section('titulo_dash')
	Categorías
@endsection

@section('styles')
@endsection

@section('titulo_page')
	Categorías
@endsection

@section('content')
	<div class="col-md-12 col-sm-12 col-xs-12">
	    <div class="x_panel">
	      	<div class="x_title">
	        	<h2><i class="fa fa-plus-square"></i> Modificar Categoría</h2>
	        	<div class="clearfix"></div>
	      	</div>
	      	<div class="x_content row">
	      		@if(count($errors)!= 0)
		            <div class="alert alert-warning text-white" role="alert">
						@foreach ($errors->all() as $error)
							<div>{{ $error }}</div>
						@endforeach
		            </div>
		        @endif
		        @include('includes.alert')
	          	<!-- Formulario EDIT CATEGORY -->
	          	<div class="col-md-10 col-md-offset-1 col-xs-12">
	          		{!! Form::model($object, ['route'=>['categories.update', $object->id],'method'=>'PUT','class'=>'form-horizontal']) !!}
	          		{!! csrf_field() !!}
	          		<div class="form-group">
                        <label for="name">Nombre *</label>
                        {!! Form::text('name',null,['class'=>'form-control', 'placeholder'=>'', 'required'=>'true']) !!}
                    </div>
                    <div class="form-group">
                        <label for="slug">Slug *</label>
                        {!! Form::text('slug',null,['class'=>'form-control', 'placeholder'=>'', 'required'=>'true']) !!}
                    </div>
                    {!! Form::submit('Actualizar Categoría',['class'=>'center-block btn btn-success']) !!}
		          	{!! Form::close() !!}
	          	</div>
	      	</div>
		</div>
	</div>
@endsection

@section('scripts')
@endsection

resources/views/templates-admin/entradas/categorias/index.blade.php
@extends('layouts.admin.dashboard')

@section('titulo_dash')
	Categorías
@endsection

@section('style')
@endsection

@section('titulo_page')
	Categorías
@endsection

@section('content')
	<div class="col-md-12 col-sm-12 col-xs-12">
	    <div class="x_panel">
	      	<div class="x_title">
	        	<h2><i class="fa fa-list"></i> Listar Categorías</h2>
	        	<div class="clearfix"></div>
	      	</div>
	      	<div class="x_content row">
	      		@include('includes.alert')
	          	<div class="col-xs-12">
					<div class="table-responsive">
					    <table id="example" class="table table-striped table-bordered dataTable" cellspacing="0" width="100%">
					        <thead>
						        <tr>
						        	<th>#</th>
						            <th>Nombre</th>
						            <th>Slug</th>
						            <th>Numero de Entradas</th>
						            <th>Acción</th>
						        </tr>
					        </thead>
					        <tbody>
					        @forelse($objects as $object)
					            <tr>
					            	<td>{{$loop->iteration}}</td>
									<td>{{$object->name}}</td>
									<td>{{$object->slug}}</td>
									<td>@if(count($object->blogs))({{$object->blogs->count()}})@else Sin entradas @endif</td>
									<td style="width:10%">
										<ul style="list-style: none;padding-left: 0;">
											<li style="display:inline-block;vertical-align: top">
												{!! Form::open(['route'=>['categories.destroy',$object->id],'method'=>'DELETE'])!!}
												{{ csrf_field() }}
								               		<button onclick="return confirm('¿Está seguro de eliminar permanentemente una categoría?');" class="btn btn-danger btn-block text-left" type="submit"><i class="fa fa-remove" aria-hidden="true"></i></button>
								                {!! Form::close() !!}
						            		</li>
						            		<li style="display:inline-block">
												<a href="{{URL::route('categories.edit',$object->id)}}" class="btn btn-primary btn-block text-left"><i class="fa fa-pencil"></i></a>
											</li>
										</ul>
									</td>
					            </tr>
					        @empty
					            <div class="alert alert-dismissable alert-warning text-white">
					                <button type="button" class="close" data-dismiss="alert">×</button>
					                <h4>Mensaje del sistema!</h4>
					                <p>Ups!, no se encontraron Categorías.</p>
					            </div>
					            <td colspan="6">No hay Categorías para mostrar</td>
					        @endforelse
					        </tbody>
					    </table>
					</div>		      		    			
	          	</div>
	      	</div>
		</div>
	</div>
@endsection

@section('script')
@endsection